# 施肥机配置文件 (Fertilizer Configuration)

implement:
  type: "Fertilizer"
  name: "Kuhn Axis 40.2 H-EMC"
  work_width: 28.0 # 工作宽度 (米)

  # ISOBUS 通信参数
  isobus:
    destination_address: 0x27 # 假设的ISOBUS设备地址
    pgn_rate_control: 0xEF02   # 假设的速率控制PGN
    pgn_enable_control: 0xEF03 # 假设的启停控制PGN

  # 作业参数
  parameters:
    min_rate_kg_ha: 20.0   # 最小施肥率 (kg/ha)
    max_rate_kg_ha: 500.0  # 最大施肥率 (kg/ha)
    default_rate_kg_ha: 150.0 # 默认施肥率

