# config/battery_params.yaml
# 电池系统参数配置

# 基本参数
nominal_capacity: 200.0    # 标称容量 (Ah)
nominal_voltage: 307.2     # 标称电压 (V)
max_voltage: 350.4         # 最大电压 (V)
min_voltage: 268.8         # 最小电压 (V)
max_charge_current: 100.0  # 最大充电电流 (A)
max_discharge_current: 300.0 # 最大放电电流 (A)
internal_resistance: 0.05  # 内阻 (Ω)

# 热参数
thermal_mass: 50000.0      # 热质量 (J/K)
heat_transfer_coeff: 100.0 # 传热系数 (W/K)
max_temperature: 60.0      # 最高工作温度 (°C)
min_temperature: -20.0     # 最低工作温度 (°C)

# 老化参数
capacity_fade_factor: 1e-6 # 容量衰减系数
resistance_growth_factor: 1e-7 # 内阻增长系数
self_discharge_rate: 2.0   # 自放电率 (%/月)

# 电芯参数
cell_count: 96             # 电芯数量
cell_nominal_voltage: 3.2  # 电芯标称电压 (V)
cell_max_voltage: 3.65     # 电芯最大电压 (V)
cell_min_voltage: 2.8      # 电芯最小电压 (V)
cell_capacity: 2.083       # 电芯容量 (Ah)

# 保护参数
over_voltage_threshold: 3.7  # 过压保护阈值 (V/cell)
under_voltage_threshold: 2.7 # 欠压保护阈值 (V/cell)
over_temperature_threshold: 65.0 # 过温保护 (°C)
under_temperature_threshold: -25.0 # 低温保护 (°C)

# 学习参数
learning_rate: 0.01        # 学习率
estimation_window: 1000    # 估计窗口大小
calibration_interval: 3600 # 校准间隔 (秒)