# Fault Detection Rules

faults:
  - id: "F001"
    name: "Engine Overheat"
    source: "Engine ECU"
    priority: "High"
    condition: "engine_temp > 105.0"
    action: "ReduceTorque"

  - id: "F002"
    name: "CAN Bus Communication Lost"
    source: "CAN Manager"
    priority: "Critical"
    condition: "can_bus_status == 'Offline'"
    action: "EmergencyStop"

  - id: "I001"
    name: "Implement Disconnected"
    source: "ISOBUS Adapter"
    priority: "Medium"
    condition: "implement_status == 'Disconnected'"
    action: "StopImplement"

