prediction_strategies:
  # 策略配置
  machine_learning:
    enabled: true
    model_path: "models/ml_predictor.tflite"
    calibration_data: "data/ml_calibration.csv"
    update_interval: 1000
    min_confidence: 0.6
    fallback_enabled: true

  nmpc_optimization:
    enabled: true
    horizon: 5.0
    time_steps: 50
    max_iterations: 10
    sampling_time: 0.1
    warm_start: true
    realtime_mode: true

  hybrid_mode:
    enabled: true
    ml_weight: 0.4
    nmpc_weight: 0.6
    fusion_method: "weighted_average"
    dynamic_weighting: true

  fallback_mode:
    enabled: true
    method: "physical_model"
    max_error_threshold: 0.3
    activation_timeout: 5.0

# 策略切换参数
strategy_switching:
  evaluation_interval: 60.0
  hysteresis: 0.1
  min_duration: 30.0
  performance_window: 300.0

# 性能监控
performance_monitoring:
  tracking_enabled: true
  sampling_rate: 1.0
  history_size: 1000
  alert_threshold: 0.25
  recalibration_interval: 3600.0

# NMPC权重配置
nmpc_weights:
  position: 10.0
  velocity: 5.0
  heading: 2.0
  control_effort: 0.1
  constraint_violation: 100.0