# config/vehicle_params.yaml
# 车辆动力学参数配置

# 质量参数
mass: 8000.0              # 总质量 (kg)
sprung_mass: 6000.0       # 簧载质量 (kg)
unsprung_mass: 2000.0     # 非簧载质量 (kg)
inertia_xx: 4000.0        # 绕X轴转动惯量 (kg·m²)
inertia_yy: 12000.0       # 绕Y轴转动惯量 (kg·m²)
inertia_zz: 10000.0       # 绕Z轴转动惯量 (kg·m²)
cg_height: 1.2            # 重心高度 (m)
wheelbase: 3.5            # 轴距 (m)
track_width: 2.0          # 轮距 (m)

# 轮胎参数
wheel_radius: 0.9         # 车轮半径 (m)
tire_stiffness: 300000.0  # 轮胎刚度 (N/m)
tire_damping: 5000.0      # 轮胎阻尼 (N·s/m)
rolling_resistance: 0.08  # 滚动阻力系数
max_tire_force: 20000.0   # 最大轮胎力 (N)

# 悬挂参数
spring_stiffness: 150000.0 # 弹簧刚度 (N/m)
damping_coefficient: 15000.0 # 阻尼系数 (N·s/m)
suspension_travel: 0.3     # 悬挂行程 (m)

# 空气动力学
frontal_area: 6.5         # 迎风面积 (m²)
drag_coefficient: 0.8     # 风阻系数
lift_coefficient: 0.2     # 升力系数

# 传动系统
final_drive_ratio: 15.0   # 主减速比
transmission_efficiency: 0.92 # 传动效率

# 性能限制
max_speed: 40.0           # 最大速度 (km/h)
max_acceleration: 3.0     # 最大加速度 (m/s²)
max_deceleration: 6.0     # 最大减速度 (m/s²)
max_gradeability: 30.0    # 最大爬坡度 (%)
max_lateral_acceleration: 3.0 # 最大横向加速度 (m/s²)

# 稳定性参数
roll_stability_threshold: 0.3  # 横滚稳定性阈值 (rad)
yaw_stability_threshold: 1.0   # 横摆稳定性阈值 (rad/s)
slip_stability_threshold: 0.3  # 滑移稳定性阈值

# 自适应学习参数
learning_rate: 0.05       # 学习率
mass_estimation_window: 100 # 质量估计窗口
friction_estimation_window: 50 # 摩擦估计窗口