name: VCU CMake Build and Test

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        build_type: [Release, Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
          /var/cache/apt
        key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Update package lists
      run: |
        sudo apt-get update

    - name: Install basic build tools
      run: |
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          wget \
          git

    - name: Install Eigen3
      run: |
        echo "Installing Eigen3..."
        sudo apt-get install -y libeigen3-dev
        
        # 验证安装
        if [ -d "/usr/include/eigen3" ]; then
          echo "✓ Eigen3 headers found at /usr/include/eigen3"
          ls -la /usr/include/eigen3/
        else
          echo "✗ Eigen3 headers not found, trying alternative installation..."
          
          # 如果apt安装失败，从源码编译安装
          cd /tmp
          wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
          tar -xzf eigen-3.4.0.tar.gz
          cd eigen-3.4.0
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo make install
          
          # 创建符号链接到标准位置
          sudo ln -sf /usr/local/include/eigen3 /usr/include/eigen3
        fi
        
        # 最终验证
        if [ -f "/usr/include/eigen3/Eigen/Dense" ]; then
          echo "✓ Eigen3 installation verified"
        else
          echo "✗ Eigen3 installation failed"
          exit 1
        fi

    - name: Install other dependencies
      run: |
        sudo apt-get install -y \
          libgtest-dev \
          libgmock-dev \
          lcov \
          cppcheck \
          clang-format \
          valgrind

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.20'

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -G Ninja

    - name: Build project
      run: |
        cmake --build ${{github.workspace}}/build \
          --config ${{ matrix.build_type }} \
          --parallel $(nproc)

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: |
        ctest --output-on-failure --parallel $(nproc)

    - name: Test executable
      working-directory: ${{github.workspace}}/build
      run: |
        ./vcu_main

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-artifacts-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/vcu_main
          build/system_test
          build/compile_commands.json
        retention-days: 7
